package com.sgp.controller.licitacao;

import com.sgp.model.licitacao.Licitacao;
import com.sgp.repository.licitacao.LicitacaoRepository;
import com.sgp.repository.licitacao.LicitacaoItemRepository;
import com.sgp.service.licitacao.LicitacaoService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.math.BigDecimal;
import com.sgp.model.licitacao.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest @AutoConfigureMockMvc @Transactional
class LicitacaoControllerTest {
 @Autowired MockMvc mvc;@Autowired LicitacaoService service;@Autowired LicitacaoRepository repositorio;@Autowired LicitacaoItemRepository itens;
 private Licitacao nova(){Licitacao l=new Licitacao();l.setOrgao("Prefeitura");l.setNumeroEdital("10/2026");l.setObjeto("Material hospitalar");l.setDataDisputa(LocalDateTime.now().plusDays(5));return service.criar(l);}
 private Licitacao novaEmAndamento(){Licitacao l=new Licitacao();l.setOrgao("Prefeitura em disputa");l.setNumeroEdital("11/2026");l.setObjeto("Material hospitalar");l.setDataDisputa(LocalDateTime.now().minusDays(1));return service.criar(l);}
 @Test @WithMockUser(roles="USUARIO") void renderizaDashboardFormularioEDetalhes()throws Exception{Licitacao l=nova();mvc.perform(get("/licitacoes")).andExpect(status().isOk()).andExpect(view().name("licitacoes/dashboard")).andExpect(content().string(org.hamcrest.Matchers.containsString("id=\"licitacao-kanban\""))).andExpect(content().string(org.hamcrest.Matchers.not(org.hamcrest.Matchers.containsString("Dashboard / Kanban"))));mvc.perform(get("/licitacoes/nova")).andExpect(status().isOk()).andExpect(view().name("licitacoes/formulario")).andExpect(content().string(org.hamcrest.Matchers.containsString("Importar dados do PNCP"))).andExpect(content().string(org.hamcrest.Matchers.containsString("id=\"linkEdital\""))).andExpect(content().string(org.hamcrest.Matchers.containsString("id=\"itensPncpJson\""))).andExpect(content().string(org.hamcrest.Matchers.containsString("id=\"preview-itens-pncp\""))).andExpect(content().string(org.hamcrest.Matchers.containsString("Todos os itens serão carregados"))).andExpect(content().string(org.hamcrest.Matchers.not(org.hamcrest.Matchers.containsString("id=\"selecionar-todos-pncp\"")))).andExpect(content().string(org.hamcrest.Matchers.containsString("id=\"carregando-pncp\""))).andExpect(content().string(org.hamcrest.Matchers.containsString("Consultando o PNCP"))).andExpect(content().string(org.hamcrest.Matchers.containsString("Dados gerais"))).andExpect(content().string(org.hamcrest.Matchers.containsString("Itens da licitação")));mvc.perform(get("/licitacoes/"+l.getId())).andExpect(status().isOk()).andExpect(view().name("licitacoes/detalhes")).andExpect(content().string(org.hamcrest.Matchers.containsString("Material hospitalar")));}
 @Test @WithMockUser(roles="USUARIO") void usuarioComumNaoVeNemExcluiLicitacaoEmAndamento()throws Exception{
  Licitacao l=novaEmAndamento();
  String acao="/licitacoes/"+l.getId()+"/excluir";
  mvc.perform(get("/licitacoes")).andExpect(status().isOk())
   .andExpect(content().string(org.hamcrest.Matchers.containsString("Prefeitura em disputa")))
   .andExpect(content().string(org.hamcrest.Matchers.not(org.hamcrest.Matchers.containsString(acao))));
  mvc.perform(get("/licitacoes/"+l.getId())).andExpect(status().isOk())
   .andExpect(content().string(org.hamcrest.Matchers.not(org.hamcrest.Matchers.containsString(acao))));
  mvc.perform(post(acao).with(csrf())).andExpect(status().isForbidden());
  org.assertj.core.api.Assertions.assertThat(repositorio.findById(l.getId())).isPresent();
 }
 @Test @WithMockUser(roles="USUARIO") void kanbanRejeitaPuloEExigeSelecaoAntesDaCotacao()throws Exception{Licitacao l=nova();mvc.perform(post("/licitacoes/"+l.getId()+"/etapa-kanban").with(csrf()).param("destino","APROVACAO")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.erro").exists());mvc.perform(post("/licitacoes/"+l.getId()+"/etapa-kanban").with(csrf()).param("destino","COTACAO")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.erro").value(org.hamcrest.Matchers.containsString("selecione os itens")));}
 @Test @WithMockUser(roles="ADMIN") void adminVeEExcluiLicitacaoEmAndamento()throws Exception{
  Licitacao l=novaEmAndamento();
  String acao="/licitacoes/"+l.getId()+"/excluir";
  mvc.perform(get("/licitacoes")).andExpect(status().isOk())
   .andExpect(content().string(org.hamcrest.Matchers.containsString("action=\""+acao+"\"")));
  mvc.perform(get("/licitacoes/"+l.getId())).andExpect(status().isOk())
   .andExpect(content().string(org.hamcrest.Matchers.containsString("action=\""+acao+"\"")));
  mvc.perform(post(acao).with(csrf())).andExpect(status().is3xxRedirection());
  org.assertj.core.api.Assertions.assertThat(repositorio.findById(l.getId())).isEmpty();
 }
 @Test @WithMockUser(roles="USUARIO") void renderizaTodasAsAbasDoFluxo()throws Exception{Licitacao l=nova();Long item=service.salvarItem(l.getId(),null,1,"Luva",BigDecimal.TEN,"CX",BigDecimal.ONE).getId();service.salvarCotacao(l.getId(),item,null,null,"Fornecedor",BigDecimal.ONE,java.time.LocalDate.now(),null);service.selecionarItensETransicionarParaCotacao(l.getId(),java.util.List.of(item),null);service.transicionar(l.getId(),EtapaLicitacao.APROVACAO,null);service.decidirItem(l.getId(),item,DecisaoItem.APROVADO,BigDecimal.ONE,BigDecimal.ZERO,"estratégia");service.transicionar(l.getId(),EtapaLicitacao.DEFINICAO,null);service.transicionar(l.getId(),EtapaLicitacao.PARTICIPACAO,null);for(String aba:new String[]{"cadastro","cotacao","aprovacao","definicao","participacao","historico","anexos"})mvc.perform(get("/licitacoes/"+l.getId()).param("aba",aba)).andExpect(status().isOk()).andExpect(view().name("licitacoes/detalhes"));}
 @Test @WithMockUser(roles="USUARIO") void cadastraAposPreenchimentoEAbreLinkPncpSalvo()throws Exception{String link="https://pncp.gov.br/app/editais/46374500000194/2026/7477";mvc.perform(post("/licitacoes").with(csrf()).param("orgao","Órgão ajustado manualmente").param("numeroEdital","30").param("uasg","090110").param("modalidade","Pregão - Eletrônico").param("objeto","Aquisição de medicamentos").param("dataDisputa","2026-09-24T09:00").param("valorEstimadoTotal","0.00").param("linkEdital",link).param("prazoEntrega","15 dias").param("precisaAmostra","true").param("observacoes","Conferido pelo usuário")).andExpect(status().is3xxRedirection());Licitacao salva=repositorio.findAll().stream().filter(l->link.equals(l.getLinkEdital())).findFirst().orElseThrow();org.assertj.core.api.Assertions.assertThat(salva.getOrgao()).isEqualTo("Órgão ajustado manualmente");org.assertj.core.api.Assertions.assertThat(salva.getPrazoEntrega()).isEqualTo("15 dias");org.assertj.core.api.Assertions.assertThat(salva.getObservacoes()).isEqualTo("Conferido pelo usuário");mvc.perform(get("/licitacoes/"+salva.getId())).andExpect(status().isOk()).andExpect(content().string(org.hamcrest.Matchers.containsString("href=\""+link+"\""))).andExpect(content().string(org.hamcrest.Matchers.containsString("target=\"_blank\""))).andExpect(content().string(org.hamcrest.Matchers.containsString("rel=\"noopener noreferrer\"")));}
 @Test @WithMockUser(roles="USUARIO") void cadastraItensConsultadosNoPncpJuntoComALicitacao()throws Exception{String link="https://pncp.gov.br/app/editais/46374500000194/2026/7477";String json="[{\"numeroItem\":1,\"descricao\":\"Medicamento A\",\"quantidade\":9000,\"unidade\":\"Comprimido\",\"valorReferencia\":0.25},{\"numeroItem\":2,\"descricao\":\"Medicamento B\",\"quantidade\":50,\"unidade\":\"Frasco\",\"valorReferencia\":12.30}]";mvc.perform(post("/licitacoes").with(csrf()).param("orgao","Secretaria de Saúde").param("numeroEdital","30").param("objeto","Aquisição de medicamentos").param("dataDisputa","2026-09-24T09:00").param("linkEdital",link).param("linkItensPncp",link).param("itensPncpJson",json)).andExpect(status().is3xxRedirection()).andExpect(flash().attribute("mensagem","Licitação cadastrada com 2 itens do PNCP. Selecione quais seguirão para Cotação."));Licitacao salva=repositorio.findAll().stream().filter(l->link.equals(l.getLinkEdital())).findFirst().orElseThrow();var cadastrados=itens.findByLicitacaoIdOrderByNumeroItem(salva.getId());org.assertj.core.api.Assertions.assertThat(cadastrados).hasSize(2);org.assertj.core.api.Assertions.assertThat(cadastrados.get(0).getDescricao()).isEqualTo("Medicamento A");org.assertj.core.api.Assertions.assertThat(cadastrados.get(0).getQuantidade()).isEqualByComparingTo("9000");org.assertj.core.api.Assertions.assertThat(cadastrados.get(0).getUnidade()).isEqualTo("Comprimido");org.assertj.core.api.Assertions.assertThat(cadastrados.get(0).getValorReferencia()).isEqualByComparingTo("0.25");}
 @Test @WithMockUser(roles="USUARIO") void selecionaNaSegundaPaginaSomenteOsItensQueSeguemParaCotacao()throws Exception{Licitacao l=nova();Long escolhido=service.salvarItem(l.getId(),null,1,"Item escolhido para cotação",BigDecimal.ONE,"UN",BigDecimal.TEN).getId();Long mantido=service.salvarItem(l.getId(),null,2,"Item mantido apenas no cadastro",BigDecimal.ONE,"UN",BigDecimal.TEN).getId();mvc.perform(get("/licitacoes/"+l.getId()).param("aba","cadastro")).andExpect(status().isOk()).andExpect(content().string(org.hamcrest.Matchers.containsString("id=\"selecionar-todos-cotacao\""))).andExpect(content().string(org.hamcrest.Matchers.containsString("form=\"form-avancar-cotacao\"")));mvc.perform(post("/licitacoes/"+l.getId()+"/etapa").with(csrf()).param("destino","COTACAO").param("selecionarItens","true").param("itemIds",escolhido.toString())).andExpect(status().is3xxRedirection());var cadastrados=itens.findByLicitacaoIdOrderByNumeroItem(l.getId());org.assertj.core.api.Assertions.assertThat(cadastrados).hasSize(2);org.assertj.core.api.Assertions.assertThat(cadastrados).filteredOn(LicitacaoItem::isSelecionadoCotacao).extracting(LicitacaoItem::getId).containsExactly(escolhido);org.assertj.core.api.Assertions.assertThat(service.obter(l.getId()).getEtapaAtual()).isEqualTo(EtapaLicitacao.COTACAO);mvc.perform(get("/licitacoes/"+l.getId()).param("aba","cotacao")).andExpect(status().isOk()).andExpect(content().string(org.hamcrest.Matchers.containsString("Item escolhido para cotação"))).andExpect(content().string(org.hamcrest.Matchers.not(org.hamcrest.Matchers.containsString("Item mantido apenas no cadastro"))));mvc.perform(get("/licitacoes")).andExpect(status().isOk()).andExpect(content().string(org.hamcrest.Matchers.containsString("<strong>1</strong> de <strong>2</strong> itens")));org.assertj.core.api.Assertions.assertThat(itens.findById(mantido)).isPresent();}
 @Test @WithMockUser(roles="USUARIO") void renderizaEdicaoImediatamenteAbaixoDoItemClicado()throws Exception{Licitacao l=nova();Long primeiro=service.salvarItem(l.getId(),null,1,"Item um",BigDecimal.ONE,"UN",BigDecimal.TEN).getId();Long segundo=service.salvarItem(l.getId(),null,2,"Item dois",BigDecimal.ONE,"UN",BigDecimal.TEN).getId();String html=mvc.perform(get("/licitacoes/"+l.getId()).param("aba","cadastro")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();int linhaPrimeiro=html.indexOf("data-item-row=\""+primeiro+"\"");int edicaoPrimeiro=html.indexOf("data-edicao-item=\""+primeiro+"\"");int linhaSegundo=html.indexOf("data-item-row=\""+segundo+"\"");org.assertj.core.api.Assertions.assertThat(linhaPrimeiro).isGreaterThanOrEqualTo(0);org.assertj.core.api.Assertions.assertThat(edicaoPrimeiro).isGreaterThan(linhaPrimeiro);org.assertj.core.api.Assertions.assertThat(linhaSegundo).isGreaterThan(edicaoPrimeiro);}
 @Test @WithMockUser(roles="USUARIO") void exibeQuantidadeNoPadraoBrasileiro()throws Exception{Licitacao l=nova();service.salvarItem(l.getId(),null,1,"Quantidade inteira",new BigDecimal("100.0000"),"UN",null);service.salvarItem(l.getId(),null,2,"Quantidade fracionada",new BigDecimal("1234.5000"),"UN",null);mvc.perform(get("/licitacoes/"+l.getId()).param("aba","cadastro")).andExpect(status().isOk()).andExpect(content().string(org.hamcrest.Matchers.containsString("<td>100</td>"))).andExpect(content().string(org.hamcrest.Matchers.containsString("<td>1.234,5</td>")));}
 @Test @WithMockUser(roles="USUARIO") void exibeCampoParaNomearAnexo()throws Exception{Licitacao l=nova();mvc.perform(get("/licitacoes/"+l.getId()).param("aba","anexos")).andExpect(status().isOk()).andExpect(content().string(org.hamcrest.Matchers.containsString("Nome do anexo *"))).andExpect(content().string(org.hamcrest.Matchers.containsString("name=\"nome\"")));}
 @Test @WithMockUser(roles="USUARIO") void portfolioPermiteBuscarCnpjOuCadastrarManualmente()throws Exception{mvc.perform(get("/licitacoes/portfolio").param("aba","fornecedores")).andExpect(status().isOk()).andExpect(content().string(org.hamcrest.Matchers.containsString("id=\"buscar-fornecedor-cnpj\""))).andExpect(content().string(org.hamcrest.Matchers.containsString("id=\"form-novo-fornecedor\""))).andExpect(content().string(org.hamcrest.Matchers.containsString("continue preenchendo o cadastro manualmente")));}
 @Test @WithMockUser(roles="USUARIO") void informaNumerosAntesDeBuscarNoPncp()throws Exception{
  String html=mvc.perform(get("/licitacoes/nova")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();
  org.assertj.core.api.Assertions.assertThat(html.indexOf("id=\"numeros-itens-pncp\"")).isGreaterThanOrEqualTo(0).isLessThan(html.indexOf("id=\"buscar-dados-pncp\""));
 }
}
